version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - drupalsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
    networks:
      - drupalsite
  # php - apache - drupal
  backend:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
      - '9000:9000'
    environment:
      EXAMPLE: db
    networks:
      - drupalsite
    working_dir: /var/www/html
    volumes:
      - ./server:/var/www/html
networks:
  drupalsite:
volumes:
  db_data:


# phpmyadmin user: root, password: password

# sudo docker-compose up
# sudo docker-compose down

# if have problems with database delete the volume with
# sudo docker system prune --force --volumes

# puts in the drupal installation host: db, user: user, password: password, database: drupal

# delete all info

# sudo docker-compose down
# sudo docker rmi $(sudo docker images -q) -f
# sudo docker volume prune

# for import database from sql file:

# sudo docker ps => get id of the mysql container
# sudo docker cp seed/backup.sql containerId:/tmp/backup.sql
# sudo docker exec -it containerId /bin/bash
# mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" "$MYSQL_DATABASE" < /tmp/backup.sql
