apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitcoind-vol
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi #Size of the volume
  accessModes:
    - ReadWriteOnce #type of access
  hostPath:
    path: "/home/anderson/bitcoind" #host location
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcoind-vol-cla
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

# kubectl create namespace bitcoind

# kubectl apply -f /home/anderson/pods/bitcoind-volume.yml --namespace=bitcoind

# kubectl get pvc --namespace=bitcoind

# kubectl get pv --namespace=bitcoind

# kubectl delete pvc bitcoind-vol-cla --namespace=bitcoind
# kubectl delete pvc bitcoind-vol --namespace=bitcoind