apiVersion: v1
kind: Pod
metadata:
  name: bitcoind
  labels:
    app: web
spec:
  containers:
    - name: bitcoind
      image: amacneil/bitcoin
      tty: true
      stdin: true
      ports:
        - containerPort: 8332
        - containerPort: 8333
        - containerPort: 18332
        - containerPort: 18333
      volumeMounts:
        - name: bitcoind
          mountPath: /data
  volumes:
    - name: bitcoind
      persistentVolumeClaim:
        claimName: bitcoind-vol-cla


# kubectl create namespace bitcoind

# kubectl apply -f /home/anderson/pods/bitcoind-pod.yml --namespace=bitcoind

# kubectl get all --all-namespaces -> list everything

# kubectl describe pod bitcoind --namespace=bitcoind 

# kubectl --namespace=bitcoind get pods

# kubectl -n kube-system logs -f bitcoind --namespace=bitcoind 

# install this: sudo apt-get install socat
# kubectl port-forward bitcoind 8333:8333 --namespace=bitcoind 
# kubectl port-forward bitcoind 8332:8332 --namespace=bitcoind 
# kubectl port-forward bitcoind 18332:18332 --namespace=bitcoind 
# kubectl port-forward bitcoind 18333:18333 --namespace=bitcoind 

# kubectl delete pods bitcoind --namespace=bitcoind

# kubectl exec --namespace=bitcoind -it bitcoind -- /bin/bash

# kubectl exec -it bitcoind --namespace=bitcoind -- bitcoind -testnet

# kubectl exec -it bitcoind --namespace=bitcoind -- sh
