apiVersion: v1
kind: PersistentVolume
metadata:
  name: ethereum-vol
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi #Size of the volume
  accessModes:
    - ReadWriteOnce #type of access
  hostPath:
    path: "/home/anderson/ethereum" #host location
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ethereum-vol-cla
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

# kubectl create namespace ethereum

# kubectl apply -f /home/anderson/pods/ethereum-volume.yml --namespace=ethereum

# kubectl get pvc --namespace=ethereum

# kubectl get pv --namespace=ethereum

# kubectl delete pvc ethereum-vol-cla --namespace=ethereum
# kubectl delete pvc ethereum-vol --namespace=ethereum