# v1

FROM rabbitmq:3.7.15-management-alpine

# commands

# docker build -t rabbitmq-test .

# docker run -d --hostname my-rabbit --name rabbitmq-test-container rabbitmq-test:3

# run with user and password data

# docker run -d --hostname my-rabbit --name rabbitmq-test-container -e RABBITMQ_DEFAULT_USER=user -e RABBITMQ_DEFAULT_PASS=password -p 4369:4369 -p 5671:5671 -p 5672:5672 -p 15671:15671 -p 15672:15672 rabbitmq-test

# console managment in port 15671 or 15671

# docker logs rabbitmq-test-container